"""Learning API routes — surface refinement proposals, behavioral drift, and outcomes.

Exposes the learning loop subsystem (feedback patterns, proposal review,
behavioral drift, outcome snapshots, library similarity) as HTTP endpoints
for the frontend Learning page.
"""

import logging
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional

from backend.api.deps import get_config, get_llm
from backend.core.db_v2 import ScreenerV2DB

router = APIRouter(prefix="/learning", tags=["learning"])
log = logging.getLogger("fundops.api.learning")


def _get_db() -> ScreenerV2DB:
    """Get the v2 database instance."""
    config = get_config()
    db_path = config.resolved.get("db_path", str(Path.home() / ".fundops" / "fundops.db"))
    return ScreenerV2DB(db_path=db_path)


# ---------------------------------------------------------------------------
# GET /learning/proposals — pending refinement proposals + stats
# ---------------------------------------------------------------------------

@router.get("/proposals")
async def get_proposals():
    """Get pending refinement proposals and aggregate stats.

    Returns proposals generated by the feedback loop (Loop 1) that
    are awaiting user accept/reject, plus overall proposal stats.
    """
    db = _get_db()
    try:
        constitution = db.get_active_constitution()
        constitution_id = constitution.get("id") if constitution else None
        proposals = db.get_pending_proposals(constitution_id=constitution_id)
        stats = db.get_proposal_stats()
    except Exception as e:
        log.error(f"Failed to fetch proposals: {e}")
        db.close()
        raise HTTPException(500, f"Failed to fetch proposals: {e}")
    finally:
        db.close()

    return {
        "proposals": proposals,
        "stats": stats,
        "count": len(proposals),
    }


# ---------------------------------------------------------------------------
# POST /learning/proposals/{proposal_id} — accept or reject a proposal
# ---------------------------------------------------------------------------

class ProposalAction(BaseModel):
    action: str  # "accept" or "reject"
    reason: Optional[str] = None


@router.post("/proposals/{proposal_id}")
async def resolve_proposal(proposal_id: str, body: ProposalAction):
    """Accept or reject a refinement proposal.

    Accept flow:
      1. Generate refined scoring code from the proposal (requires LLM)
      2. Create a new strategy version with the refined code
      3. Update the constitution's active_version_id
      4. Mark proposal as accepted with the new version id

    Reject flow:
      1. Mark proposal as rejected with optional reason
    """
    if body.action not in ("accept", "reject"):
        raise HTTPException(400, "action must be 'accept' or 'reject'")

    db = _get_db()
    try:
        proposal = db.get_proposal(proposal_id)
        if not proposal:
            raise HTTPException(404, f"Proposal {proposal_id} not found")

        if proposal.get("status") != "pending":
            raise HTTPException(
                409, f"Proposal {proposal_id} already resolved with status '{proposal.get('status')}'"
            )

        if body.action == "reject":
            updated = db.resolve_proposal(proposal_id, user_response="rejected")
            log.info(f"Proposal {proposal_id} rejected. Reason: {body.reason or 'none'}")
            return {"proposal": updated, "action": "rejected"}

        # --- Accept flow ---
        # Get current scoring code from the active version
        constitution = db.get_active_constitution()
        active_version_id = constitution.get("active_version_id") if constitution else None
        current_code = ""
        if active_version_id:
            version = db.get_version(active_version_id)
            if version:
                current_code = version.get("scoring_code", "")

        if not current_code:
            # No existing scoring code — accept the proposal but skip code generation
            updated = db.resolve_proposal(proposal_id, user_response="accepted")
            log.info(f"Proposal {proposal_id} accepted (no active scoring code to refine)")
            return {
                "proposal": updated,
                "action": "accepted",
                "note": "No active scoring code found — proposal recorded but no code generated.",
            }

        # Generate refined code using LLM
        # TODO: This requires an async LLM call. For now, attempt it and fall back gracefully.
        try:
            from backend.learning.feedback_loop import generate_refined_code

            llm = get_llm()
            strategy = None
            if constitution:
                strategy = {
                    "north_star": constitution.get("north_star"),
                    "style_identity": constitution.get("style_identity"),
                    "must_have_signals": constitution.get("must_have_signals"),
                    "anti_signals": constitution.get("anti_signals"),
                }

            new_code = await generate_refined_code(llm, current_code, proposal, strategy)

            if new_code:
                # Create a new strategy version
                import uuid
                new_version_id = f"v-{uuid.uuid4().hex[:8]}"
                constitution_id = constitution.get("id") if constitution else None

                # Determine strategy_id and version_number
                strategy_id = constitution_id or "default"
                current_version = db.get_version(active_version_id)
                version_number = (current_version.get("version_number", 0) + 1) if current_version else 1

                version_row = db.create_version(
                    version_id=new_version_id,
                    strategy_id=strategy_id,
                    version_number=version_number,
                    scoring_code=new_code,
                    label_map=current_version.get("label_map") if current_version else None,
                    explanation=f"Refined from proposal {proposal_id}: {proposal.get('proposal', '')}",
                )
                actual_vid = version_row["id"] if version_row else new_version_id

                # Activate the new version on the constitution
                if constitution_id:
                    db.update_constitution(constitution_id, active_version_id=actual_vid)

                updated = db.resolve_proposal(
                    proposal_id, user_response="accepted", applied_version_id=actual_vid
                )
                log.info(f"Proposal {proposal_id} accepted. New version: {actual_vid}")
                return {
                    "proposal": updated,
                    "action": "accepted",
                    "new_version_id": actual_vid,
                }
            else:
                # Code generation failed validation — do NOT mark as accepted
                log.warning(f"Proposal {proposal_id}: code generation failed validation")
                return JSONResponse(
                    status_code=500,
                    content={
                        "error": "Code generation failed validation",
                        "detail": "Proposal was not accepted because refined code could not be generated.",
                    },
                )

        except Exception as e:
            # Code generation error — do NOT mark as accepted
            log.warning(f"Code generation failed for proposal {proposal_id}: {e}")
            return JSONResponse(
                status_code=500,
                content={
                    "error": "Code generation failed",
                    "detail": f"Proposal was not accepted: {e}",
                },
            )

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"Failed to resolve proposal {proposal_id}: {e}")
        raise HTTPException(500, f"Failed to resolve proposal: {e}")
    finally:
        db.close()


# ---------------------------------------------------------------------------
# GET /learning/drift — behavioral drift analysis (Loop 2)
# ---------------------------------------------------------------------------

@router.get("/drift")
async def get_drift():
    """Get behavioral drift analysis: stated constitution vs actual IC decisions.

    Requires at least 5 IC decisions to produce meaningful analysis.
    Returns empty result with a message if insufficient data.
    """
    db = _get_db()
    try:
        constitution = db.get_active_constitution()
        if not constitution:
            return {
                "has_enough_data": False,
                "decisions_analyzed": 0,
                "summary": "No active constitution found. Create a strategy first.",
                "style_drift": [],
                "signal_drift": [],
                "anti_signal_violations": [],
                "override_patterns": [],
                "approval_profile": {},
            }

        from backend.learning.behavioral import analyze_drift

        drift = await analyze_drift(db, constitution)
        return drift

    except Exception as e:
        log.error(f"Drift analysis failed: {e}")
        raise HTTPException(500, f"Drift analysis failed: {e}")
    finally:
        db.close()


# ---------------------------------------------------------------------------
# GET /learning/outcomes — recent outcome snapshots
# ---------------------------------------------------------------------------

@router.get("/outcomes")
async def get_outcomes(ticker: str = None, limit: int = 50):
    """Get recent outcome snapshots tracking how screened stocks performed.

    Outcome snapshots are recorded at intervals (90d, 180d, 365d, etc.)
    after stocks are screened. Returns price performance vs benchmark.
    """
    db = _get_db()
    try:
        outcomes = db.get_outcomes_for_strategy(ticker=ticker, limit=limit)

        # Compute alpha for each outcome
        enriched = []
        for o in outcomes:
            return_pct = o.get("return_pct")
            benchmark_pct = o.get("benchmark_return_pct")
            alpha = None
            if return_pct is not None and benchmark_pct is not None:
                alpha = round(return_pct - benchmark_pct, 2)

            enriched.append({
                "ticker": o.get("ticker"),
                "screener_run_id": o.get("screener_run_id"),
                "screened_at": o.get("screened_at"),
                "check_at": o.get("check_at"),
                "days_elapsed": o.get("days_elapsed"),
                "return_pct": return_pct,
                "benchmark_return_pct": benchmark_pct,
                "alpha_pct": alpha,
                "price_at_screen": o.get("price_at_screen"),
                "price_at_check": o.get("price_at_check"),
                "thesis_integrity": o.get("thesis_integrity"),
                "goal_alignment": o.get("goal_alignment"),
            })

        return {
            "outcomes": enriched,
            "count": len(enriched),
        }

    except Exception as e:
        log.error(f"Failed to fetch outcomes: {e}")
        raise HTTPException(500, f"Failed to fetch outcomes: {e}")
    finally:
        db.close()


# ---------------------------------------------------------------------------
# POST /library/similar — find similar research entries
# ---------------------------------------------------------------------------

# This router is mounted under /api with prefix /learning, so we need
# a separate router for library endpoints at the module level, or we
# include it here with an overridden path. We use the learning router
# but with a full path override.

library_router = APIRouter(prefix="/library", tags=["library"])


class SimilarRequest(BaseModel):
    ticker: str
    sector: Optional[str] = None
    gross_margin: Optional[float] = None
    roic: Optional[float] = None
    top_k: int = 5


@library_router.post("/similar")
async def find_similar(body: SimilarRequest):
    """Find similar library entries by sector and financial metrics.

    Uses SQL-based similarity matching on sector, gross margin range (+/-10pp),
    and ROIC range (+/-5pp). Returns up to top_k matches.
    """
    db = _get_db()
    try:
        results = db.find_similar(
            ticker=body.ticker,
            sector=body.sector,
            gross_margin=body.gross_margin,
            roic=body.roic,
            top_k=body.top_k,
        )
        return {
            "query": {
                "ticker": body.ticker,
                "sector": body.sector,
                "gross_margin": body.gross_margin,
                "roic": body.roic,
            },
            "results": results,
            "count": len(results),
        }

    except Exception as e:
        log.error(f"Library similarity search failed: {e}")
        raise HTTPException(500, f"Library similarity search failed: {e}")
    finally:
        db.close()


class LibraryAskRequest(BaseModel):
    question: str
    history: list = []


@library_router.post("/ask")
async def ask_library(body: LibraryAskRequest):
    """Ask questions about your research archive using AI.

    Gathers relevant library data (thesis, IC, memos, events) and sends
    the question + context to the LLM for an informed answer.
    """
    import json as _json
    import re

    from backend.api.deps import get_llm, get_db as get_main_db

    llm = get_llm()
    if not llm.api_key:
        return {
            "answer": "AI model not configured. Set up your API key in Settings to enable Library Q&A.",
            "sources": [],
        }

    db = _get_db()
    main_db = get_main_db()

    # Extract ticker mentions from the question
    ticker_pattern = re.compile(r'\b([A-Z]{1,6})\b')
    mentioned_tickers = ticker_pattern.findall(body.question)
    # Filter out common words that look like tickers
    common_words = {"THE", "AND", "FOR", "NOT", "BUT", "ALL", "ARE", "WAS", "HAS", "HAD", "HOW", "WHY", "DID", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC", "JAN", "FEB", "MAR"}
    mentioned_tickers = [t for t in mentioned_tickers if t not in common_words]

    # Gather context from the library
    context_parts = []

    # 1. Get library stats
    try:
        stats = db.get_library_stats()
        context_parts.append(f"Library stats: {_json.dumps(stats, default=str)}")
    except Exception:
        pass

    # 2. Get data for mentioned tickers
    for ticker in mentioned_tickers[:5]:  # Max 5 tickers
        try:
            entries = db.get_library_by_ticker(ticker)
            if entries:
                for entry in entries[:3]:  # Max 3 entries per ticker
                    entry_data = entry.get("data", {})
                    if isinstance(entry_data, str):
                        try:
                            entry_data = _json.loads(entry_data)
                        except Exception:
                            pass
                    context_parts.append(
                        f"\n--- {ticker} ({entry.get('entry_type', '?')}, verdict={entry.get('verdict', '?')}) ---\n"
                        f"Expected return: {entry.get('expected_return')}%, "
                        f"Discount: {entry.get('discount_pct')}%, "
                        f"Conviction: {entry.get('conviction')}, "
                        f"Sector: {entry.get('sector')}, "
                        f"GM: {entry.get('gross_margin')}, ROIC: {entry.get('roic')}"
                    )

            # Also get agent runs for this ticker (thesis narrative, IC review)
            runs = main_db.get_runs_for_ticker(ticker) if hasattr(main_db, 'get_runs_for_ticker') else []
            for run in (runs if isinstance(runs, list) else [])[:5]:
                agent = run.get("agent", "")
                run_type = run.get("run_type", "")
                if run_type in ("job_start", "job_complete"):
                    continue
                try:
                    fo = run.get("full_output")
                    full = _json.loads(fo) if isinstance(fo, str) else (fo or {})
                    if agent == "thesis":
                        narrative = full.get("thesis_narrative", "")
                        if narrative:
                            context_parts.append(f"\n--- {ticker} THESIS ---\n{narrative[:1500]}")
                    elif agent == "ic_review":
                        review = full.get("ai_review", "")
                        verdict = full.get("verdict", "")
                        if review:
                            context_parts.append(f"\n--- {ticker} IC REVIEW ({verdict}) ---\n{review[:1000]}")
                    elif agent == "memo":
                        summary = run.get("summary", "")
                        if summary:
                            context_parts.append(f"\n--- {ticker} MEMO ---\n{summary[:500]}")
                except Exception:
                    pass
        except Exception:
            pass

    # 3. If no tickers mentioned, get recent events for general context
    if not mentioned_tickers:
        try:
            recent = db.get_recent_events(limit=20)
            for ev in (recent if isinstance(recent, list) else [])[:10]:
                context_parts.append(
                    f"{ev.get('event_type', '?')} {ev.get('ticker', '?')}: {ev.get('rationale', '')[:100]}"
                )
        except Exception:
            pass

    # Build the prompt
    context_text = "\n".join(context_parts) if context_parts else "No research data available yet."

    system_prompt = """You are the FundOps Library AI assistant. You have access to the user's research archive including screener results, thesis narratives, IC review verdicts, investment memos, and outcome tracking data.

Answer questions about their research history, investment decisions, thesis assumptions, and portfolio analysis. Be specific with data when available. Reference actual numbers, verdicts, and dates from the context.

If the user asks about a ticker, use the thesis, IC review, and memo data provided. If they ask general questions, use the library stats and recent events."""

    messages = [{"role": "system", "content": system_prompt}]

    # Add conversation history
    for msg in body.history[-10:]:
        role = msg.get("role", "user")
        if role == "ai":
            role = "assistant"
        messages.append({"role": role, "content": msg.get("content", "")})

    # Add current question with context
    messages.append({
        "role": "user",
        "content": f"""RESEARCH CONTEXT:
{context_text[:6000]}

QUESTION: {body.question}"""
    })

    try:
        result = await llm.generate_chat(
            messages=messages,
            agent="library_qa",
            reasoning_effort="medium",
        )

        sources = []
        for t in mentioned_tickers[:5]:
            sources.append({"ticker": t, "type": "library_entry"})

        db.close()
        return {
            "answer": result.text or "I couldn't generate a response. Please try again.",
            "sources": sources,
            "tokens": result.tokens_in + result.tokens_out,
            "cost": round(result.cost, 4),
        }

    except Exception as e:
        log.error(f"Library Q&A failed: {e}")
        db.close()
        return {
            "answer": f"Failed to get AI response: {str(e)}",
            "sources": [],
        }
